### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by kooy** [ruffchain/Shepherd#7]
https://testnet.ruffchain.com/tx/c0ff0640dff90fefc504fcfc971c52812da4c1dec81b295ecdc54202a20565ba

这个交易只用了 0.1 币，就写入了大量数据， 有没有安全问题？

**Comment by topelinux** [comment]
这条交易被链记录了，但是它 操作没有成功，如返回值所示
RESULT_FEE_TOO_SMALL = 30, // 操作被取消
```
 "transactionHash": "c0ff0640dff90fefc504fcfc971c52812da4c1dec81b295ecdc54202a20565ba",
"returnCode": 30, 
``` 
确实会造成节点磁盘上占用部分的大下，调用者的成本是（0.1 sys token），但是不会对状态数据库造成影响，所以从状态数据库(不受影响）的角度 是安全的。
